import LoginModal from './components/authModals/LoginModal'
import RegisterModal from './components/authModals/RegisterModal'
import Navbar from './components/navbar/Navbar'
import './globals.css'
import {Inter} from 'next/font/google'
import {Amplify} from 'aws-amplify'
import config from '../src/aws-exports'
import Sidebar from './components/sidebar/Sidebar'
import {API} from "aws-amplify";



Amplify.configure({...config, ssr: true})

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-900`}>
        <Navbar />
        <Sidebar />
        <LoginModal />
        <RegisterModal />
        {children}
      </body>
    </html>
  )
}
